spring:
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create        # turn off for custom schema.sql
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize=true:
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: false
          use_sql_comments: false
          format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false