---
- name: download and start web server
  hosts: all
  become: yes

  tasks:
  - name: Install Apache
    yum: name=httpd state=latest

  - name: Start Apache
     service: name=httpd state=started enabled=yes