package x030.EncodingHashing;


import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.apache.commons.codec.binary.Hex.encodeHex;

public class MD5Hashcode {

    public static String getMMD(String input) {
        StringBuilder builder = new StringBuilder();
        String result = "shit happens";
        try {
            MessageDigest md5 = MessageDigest.getInstance("MD5");
            md5.update(builder.toString().getBytes(UTF_8));
            result = new String(encodeHex(md5.digest(input.getBytes(UTF_8))));
            md5.reset();
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Error: " + e);
        }
        return result;

    }


    public static String getMd5(String input) {
        try {

            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }

        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Driver code
    public static void main(String args[]) throws NoSuchAlgorithmException {
        String s = "GeeksForGeeks";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
        System.out.println("Your HashCode #2 Generated by MD5 is: " + getMMD(s));
    }
}
