#welcome.message: Hello welcome 1 message
#available conn.props jdbc/h2/hibernate


#spring:
#  profiles:
#    active: h2
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookAplication
#    username: root
#    password: 12345678
#    driverClassName: com.mysql.jdbc.Driver

spring:
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create        # turn off for custom schema.sql
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true       # to show SQL query beautiful
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  mvc:
    view:
      prefix: /webPages/
      suffix: .jsp

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

---
spring:
  profiles: h2

welcome:
  message: Hello h2 profile
conn:
  prop: h2

---
spring:
  profiles: jdbc
welcome:
  message: Hello jdbc profile
conn:
  prop: jdbc

---
srping:
  profiles: hibernate
welcome:
  message: Hello hibernate profile
conn:
  prop: hibernate

---


    # outdated info for H2 settings

#jpa:
#  #            database-platform: org.hibernate.dialect.H2Dialect
#  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  hibernate:
#    ddl-auto: update
#  properties:
#    hibernate:
#      show_sql: true
#      use_sql_comments: false
#      format_sql: true