
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookAplication
#    username: root
#    password: 12345678


#welcome.message: Hello welcome 1 message
#available conn.props jdbc/h2/hibernate

spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:mysql://localhost:3306/bookAplication
    platform:
    username: root
    password: 12345678
    driverClassName: com.mysql.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: false
          use_sql_comments: false
          format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

#  mvc:
#    view:
#      prefix: /webPages/
#      suffix: .jsp




---
spring:
  profiles: h2

welcome:
  message: Hello h2 profile
conn:
  prop: h2

---
spring:
  profiles: jdbc
welcome:
  message: Hello jdbc profile
conn:
  prop: jdbc

---
srping:
  profiles: hibernate
welcome:
  message: Hello hibernate profile
conn:
  prop: hibernate

---
