INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Alek','Baldwin', 56,'somewhere in USA', 'some@mail.ko')
INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Jhon','Wick', 45,'Neo street', 'matrix@.net')
INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Matriza','Hujatriza', 19,'Russia street', 'mail@.dot.ru')
INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Jhon','Lenon', 87,'London street', 'somemail@mail.uk')
INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Crhis','Ronaldu', 35,'Madrid street', 'cr7@madridpost.es')
INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Crhis','Ronaldu', 35,'Madrid street', 'cr7@madridpost.es')
INSERT INTO myUSER (USERNAME, USERSURNAME, USERAGE, USERADRESS, EMAILADRESS) VALUES('Crhis','Ronaldu', 35,'Madrid street', 'cr7@madridpost.es')
INSERT INTO userINFO (CITY, COUNTRY, STREET, POSTALCODE) VALUES ('Los-Angeles', 'USA', 'Californica Street', 228834)
INSERT INTO userINFO (CITY, COUNTRY, STREET, POSTALCODE) VALUES ('New-York', 'USA', 'Neo Street', 899763765)
INSERT INTO userINFO (CITY, COUNTRY, STREET, POSTALCODE) VALUES ('Moscow', 'RUSSIA', 'Russia Street', 62367)
INSERT INTO userINFO (CITY, COUNTRY, STREET, POSTALCODE) VALUES ('London', 'GREAT BRITAIN', 'English street', 1102983)
INSERT INTO userINFO (CITY, COUNTRY, STREET, POSTALCODE) VALUES ('Madrid', 'SPAIN', 'Spanish street', 943022)
INSERT INTO emailTable (email, domainx, host) VALUES ('some@mail.ko', 'american', 'awsWest')
INSERT INTO emailTable (email, domainx, host) VALUES ('matrix@.net', 'american', 'awsEast')
INSERT INTO emailTable (email, domainx, host) VALUES ('mail@.dot.ru', 'russian', 'KGB')
INSERT INTO emailTable (email, domainx, host) VALUES ('somemail@mail.uk', 'english', 'mi6 secret')
INSERT INTO emailTable (email, domainx, host) VALUES ('cr7@madridpost.es', 'spanish', 'el paso')
